site_name: Approved recipes
theme:
  name: material
  palette:
    primary: grey
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Main Courses: 
      - Main Courses: main-courses/main-courses.md
      - Carbonara: main-courses/spaghetti_carbonara.md
      - Pizza: main-courses/pizza.md
      - Arrabiata: main-courses/arrabiata.md
  - Ingredients:
      - Ingredients: ingredients/ingredients.md
      - Pasta: ingredients/pasta.md
  - Appetizers: 
      - Appetizers: appetizers.md
  - Desserts: 
      - Desserts: desserts.md
      - Chocomouse: desserts/chocomouse.md
  - Soup: soup.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
