name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material  # Replace with your theme or plugins

    - name: Build and deploy
      env:
        CI: true
      run: |
        mkdocs gh-deploy --force
